
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class HowTo extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'how_to_body') {
                    return 'howToBody';
                }
                if (elementName === 'how_to_title') {
                    return 'howToTitle';
                }
                return elementName;
            })
        });
    }
}
