
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 
 */
export class Resume extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((elementName) => {
                if (elementName === 'resume_title') {
                    return 'resumeTitle';
                }
                if (elementName === 'resume_short_description') {
                    return 'resumeShortDescription';
                }
                if (elementName === 'resume_body') {
                    return 'resumeBody';
                }
                return elementName;
            })
        });
    }
}
